### ISSUE TITLE
Outdated RPM Spec

### ISSUE THREAD

**Issue by bensallen** [duosecurity/duo_unix#108]
It looks like the RPM spec file in this repo is outdated and does not match what Duo publishes at http://pkg.duosecurity.com. Additionally, the spec file in this repo is currently broken as its still trying to package libduo, and is missing shell.h, authlogin_duo.pp.bz2.

**Comment by xdesai** [comment]
Hey Ben,
Thanks for commenting on that. We originally used this specfile but have since switched to an internal method of creating the rpm and deb packages. I will make a note to remove this old specfile and see if there's any way we can produce a specfile that will actually work and include it in the repo for people who want to roll their own packages.

Thanks for keeping us honest and thanks for using Duo!

**Comment by vbscott** [comment]
Hello,
Thanks for the comment.  We ended up removing the old specfile so I am going to close out this issue.
