### ISSUE TITLE
distribution tarballs lack necessary autoconf/automake files to build

### ISSUE THREAD

**Issue by qralston** [duosecurity/duo_unix#111]
The source releases available here, as tar files:

https://github.com/duosecurity/duo_unix/releases

…do not contain the necessary autoconf/automake files to compile the package.

More specifically, the tarballs appear to be packaged after running `make maintainer-clean`, instead of after running `make distclean`.

This is an error. As per [section 16.1 of the GNU autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf.html#Basic-Installation), `make maintainer-clean` is intended for the package's developers, because it deletes files that are intended to be packaged with the distribution and require development tools to regenerate.

Running `make maintainer-clean` also throws a warning to that effect:

```
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
```

Here is the problem with expecting builders to run `autoreconf -vfi -I autotools` before building the package: the autoconf/automake tools are finicky, temperamental beasts that have a long-standing track record of poor backward *and* forward compatibility.

To put it bluntly: unless the packager is using the *exact* same versions of automake/autoconf that the developer used, there's a good chance that the packager will be unable to regenerate the files that `make maintainer-clean` removed.  This requires packagers to run autoreconf on a compatible system, scoop up the generated autoconf/automake files, and patch them into the build process. (This is what I did in my pull request #109.)

In the case of Red Hat Enterprise Linux, only RHEL7 contains recent enough versions of autoconf/automake in order to run the autoconf/automake tools to rebuild the `configure` script and the various `*.in` files. You literally _cannot build the duo_unix distribution tarballs_ on RHEL6.

It's not clear to me how the duo_unix distribution tarballs are being generated, so I can't submit a pull request that corrects the issue.  But in a nutshell, whatever process builds the release tarballs needs to run `make distclean`, *not* `make maintainer-clean`.

Thanks!

**Comment by ghstwhl** [comment]
The state of the repo is also at odds with the documentation.  The README for duo_unix is a stub that refers the user to https://duo.com/docs/duounix where the instructions say to run "./configure --with-pam --prefix=/usr && make && sudo make install" which does not work because the repo no longer contains an executable named 'configure'.  The 'official docs' make no mention of the bootstrap script that will create the configure script, let alone how do deal with trying to compile on older systems like RHEL 6.

**Comment by ghstwhl** [comment]
@DuoKristina - You are right, I was the one that had gone off script; so that's by fault the instructions don't work with the latest github release.  

Any idea why the 'latest' tarball on dl.duosecurity.com isn't actually the latest release?  It's two releases, and a year, behind the releases in the github repo.

**Comment by DuoKristina** [comment]
There are no actual code changes in the last two GitHub tagged releases, so it didn't seem worthwhile to build a new "latest" release.

**Comment by vbscott** [comment]
I am going to close this issue out.  Let us know if you have any more questions.
