### ISSUE TITLE
Broken pipe if password is wrong at first attempt

### ISSUE THREAD

**Issue by kcgthb** [duosecurity/duo_unix#118]
Hi there, 

I'd like to report the exact same issue that is described in #117, where SSH connection fails with "broken pipe" when a wrong password is initially entered. 
This happens on CentOS 7, following the instructions and using the configuration examples at https://duo.com/docs/duounix

I would also like to add that we obeserve that exact same behavior on a large variety of machines, running different distributions and using a variety of SSH authentication mechanisms (password, GSSAPI/Kerberos, pubkeys...)

Any insight would be appreciated, thanks.

**Comment by xdesai** [comment]
Hi!
This seems like it's likely a configuration issue. I quickly spun this up to test and couldn't reproduce the issue when I entered a bad password. Since we'd need to start taking a look at configuration files and log files can you please contact Duo support and we'll help resolve this for you. Here's a link with the ways to get in touch with them https://duo.com/support

Thanks for using Duo!

**Comment by kcgthb** [comment]
Unfortunately, I'm not a "site administrator", although I manage servers using Duo at my institution, so contacting Duo support directly doesn't seem to be an option.
