### ISSUE TITLE
Incorporate login_duo in OpenLDAP plugin

### ISSUE THREAD

**Issue by z-tb** [duosecurity/duo_unix#150]
I have a lot of applications running on Linux which don't support Duo natively. They *do* support LDAP (via OpenLDAP) authentication so I've been looking for a way to integrate Duo MFA into these apps without a lot of changes in code bases or configurations. I tried the LDAP Proxy, but it seems there are some unsupported LDAP tags which aren't quite ironed out yet. I ended up modifying an OpenLDAP RADIUS password plugin that we've been using for years and ran the login_duo program from within it. This required modifying the login_duo source a little bit; adding the option -n to denote "no login shell" and adding a check to allow the -f flag when being run by a non-root (slapd process) user.  This allows slapd (running as the openldap user) to run login_duo with '-f username' and test the exit code (EXIT_FAILURE or EXIT_SUCCESS) to determine if authorization should be granted or denied (in addition to successful password auth).
So far, it's working quite well in testing (well, for a single day anyway) so it's a good time to ask if anything already exists withing the Duo realm to do this?

**Comment by xdesai** [comment]
Hi!
I'm a little confused on your question. When you say if anything exists in the Duo realm to do this are you asking if there's a single linux program that does Duo 2fa and LDAP 1fa? If so, then no we don't have anything like that. Using the Authentication Proxy is major way we support putting 2fa on LDAP binds.

One other thing we often see people do is have their Linux programs use PAM for authentication. You can then include an LDAP or Radius PAM module for 1fa and then use pam_duo in that same stack for 2fa.
Let me know if I answered your question or if there's anything else you're looking for.
Best,
Xander

**Comment by z-tb** [comment]
Hi Xander,
Apologies for not being clearer. Yes, specifically a way to get AD/LDAP for the first factor and  Duo for the second factor. Some of the applications we'd like to use Duo for are web based (LDAP authentication via PHP, Ruby and Perl) while others are already covered (SSH logins) in the duo_unix package. The big piece we're missing is how to bring all of our web based applications under a Duo login. Some apps support Google authenticator, but not Duo. Others do TOTP. The A.P. doesn't currently work with all our apps, so looking for options. With the LDAP plugin, the Duo auth ends up being initiated on on the LDAP server rather than the hosted application.

**Comment by xdesai** [comment]
Thanks for providing some clarification! Using our Authentication Proxy is currently the best way to integrate Duo with LDAP specifically, and I'm sorry that it's not working for you. It would be great if you could reach out to the Duo Support team and let them know specifically what tags are not working for you. That way we can better identify and track which tags we need to add support for. They also might have some helpful ideas for you on other ways to integrate your applications with Duo. Since they are web based it's possible that using the Duo WebSDK might be a route you can take.

Here's the link for contacting support. [Duo Support](https://duo.com/support)
Here's the link for the WebSDK documentation. [Duo WebSDK](https://duo.com/docs/duoweb)

Since this issue is not a bug with the Duo Unix product I'm going to close it out. Thank you for using Duo and good luck with the rest of your Duo set up :)
-Xander
