### ISSUE TITLE
KDE Plasma and SDDM pam_duo integration failure

### ISSUE THREAD

**Issue by StarkZarn** [duosecurity/duo_unix#198]
## Summary
SDDM and KDE Plasma Polkit do not allow Duo authentication. I am currently using the pam_duo.so module in my common-auth. Everything works as expected with Gnome and GDM. It is the latest version as of yesterday.

SDDM simply shows no field to input a Duo code into and login subsequently fails. Switching to a different TTY, I can login successfully to the CLI. With fail open, I can also disconnect my network and login to a graphical KDE Plasma session without a Duo prompt.

Polkit prompts from the KDE Plasma desktop ask for a password, then subsequently show the message for Duo authentication but provide no text field to enter the code.

## Steps to reproduce
1. Install latest duo_unix version.
2. Configure /etc/pam.d/common-auth as per Duo documentation to call pam_duo.so
3. Attempt to login from SDDM greeter
4. No Duo prompt is displayed.

1. After starting a KDE Plasma session, cause a polkit prompt. i.e. Go to System Settings -- Attempt to change login screen / SDDM settings.
2. A polkit prompt is displayed asking for a password. Enter password.
3. The polkit prompt updates with Duo text
4. Observe no text field for Duo prompt is displayed.

## Specs
- OS version (ie CENTOS 7 or Ubuntu 14): Kali 2021.2 -- (I believe this is effectively the same as Debian testing)
- OS arch (ie 32 or 64): 64
- Using pam_duo or login_duo: pam_duo

**Comment by zemsten** [comment]
Two months later, this is still a problem and I haven't gotten any traction on it -- this includes in the duo community forums as well.

**Comment by mbish** [comment]
Are you able to get SDDM to send a push through Duo by putting `autopush=yes` in the configuration file ? This would allow you to approve a login from your phone without being prompted to select a second factor or enter a passcode. Getting this to work with passcode entry has the added difficulty of needing an input field which (as you mentioned) doesn't exist on SDDM.

**Comment by zemsten** [comment]
> Are you able to get SDDM to send a push through Duo by putting `autopush=yes` in the configuration file ? This would allow you to approve a login from your phone without being prompted to select a second factor or enter a passcode. Getting this to work with passcode entry has the added difficulty of needing an input field which (as you mentioned) doesn't exist on SDDM.

Yes. This works, and has been my workaround. Unfortunately though, this means that I get push notifications for all duo prompts, including on the terminal where it would be much more beneficial to use my yubikey.

So your conclusion is that this is a problem with SDDM, correct? Is there any way to have duo allow me the option for a token authentication in the terminal vs push in polkit?

**Comment by mbish** [comment]
Yeah that's correct. SDDM just doesn't have this feature and I'm not sure if it's on their road map.

To have separate behavior for terminal vs. DM login you're going to have to dig into your PAM config. In order to get yubikey authentication at the terminal I'd use something like `pam_u2f` (https://github.com/Yubico/pam-u2f). You'd put that in your `/etc/pam.d/login` file for terminal logins then you'd put `duo_unix` in SDDM's PAM file.

The exact implementation depends on what sort of terminal authentications your performing, Those instructions apply to linux `/bin/login` style authentications but you can modify this approach for things like `sudo`, `su` or a screen locker by putting the `pam_u2f` rules in their respective `/etc/pam.d/` files. 

Generally additional factors shouldn't be pushed to the facility level of the PAM stack and should instead be kept in shared common auth files for consistent system behavior and security so I'll admit that this is not ideal (this is why our documentation directs users to modify `system-auth` or `common-auth`). We have looked into supporting yubikey through Duo Unix but it's not something we've gotten to work well as of yet.

**Comment by mbish** [comment]
In general injecting additional input fields or otherwise getting additional user input on a simple username/password login form needs to be done on a case-by-case basis as there doesn't exist a standard for augmenting such forms with additional challenge-response flows.

Since we don't have plans to add support for SDDM specifically, I'm going to close this for now.

SDDM logins can be protected with Duo Unix via the `autopush = yes` configuration option in `pam_duo.conf`.
