### ISSUE TITLE
duo_unix-1.12.1-4.el8 and setuid 

### ISSUE THREAD

**Issue by macado** [duosecurity/duo_unix#236]
## Summary
I noticed that duo_unix package is now included in the EPEL repo for RHEL8.  Previously we were installing duo_unix from the official Duo Security repo that we mirror but the EPEL repo appears to contain a newer version of duo_unix (duo_unix-1.12.1-4.el8.x86_64) so a few of our systems updated to that.  This upgrade broke SSH authenication because our previous package had /usr/sbin/login_duo set to setuid.

Oct 20 19:16:51 hostname-prod-01 kernel: warning: `/usr/sbin/login_duo' has both setuid-root and effective capabilities. Therefore not raising all capabilities

When I try to ssh into a host I get this:
couldn't drop privileges: Operation not permitted

When upgrading from duo_unix-1.12.1-0.el8.x86_64 to duo_unix-1.12.1-4.el8.x86_64 it appears /usr/sbin/login_duo is no longer required to be setuid.  Is this intended behavior?   

The issue I have is we're setting /usr/sbin/login_duo to chmod 4755 via configuration management and have mismatched versions of duo_unix. Since we upgrade our environments separately this will break ssh on hosts where I've upgraded.  

On duo_unix-1.12.1-0.el8.x86_64 if unset the setuid bit on /usr/bin/login_duo then I can't read /etc/duo/login_duo.conf
Couldn't open /etc/duo/login_duo.conf: Permission denied
-rw-------    1 sshd root  479 Oct 20 19:41 login_duo.conf

If I change /etc/duo/login_duo.conf to 644 (which I know i dont want to do) I get this..
/etc/duo/login_duo.conf must be readable only by user 'ssh-user'

## Steps to reproduce
1. Install duo_unix-1.12.1-4.el8.x86_64 from EPEEL on RHEL8
2.  chmod u+s /usr/sbin/login_duo

## Specs
- OS version: RHEL 8.6
- OS arch: x86_64
- Using: login_duo: duo_unix-1.12.1-4.el8.x86_64 from EPEL

**Comment by AaronAtDuo** [comment]
@macado The new-ish EPEL package of Duo Unix is not published by Duo Security / Cisco.  It was published by an individual not affiliated with Duo, and without notifying or consulting us.  And due to it A) being in the EPEL packages and B) having a higher version, it is taking precedence over the Duo-published packages.  We've had a number of customers affected by this, because the EPEL packages are not identical to the Duo packages, and some functionality is left out or altered.

We are working with the individual who published the packages and they are being receptive to requests to reintroduce functionality, but the best short-term plan for you may be to set up your system to ignore the EPEL packages and stick to the official Duo ones for now.

**Comment by macado** [comment]
Thanks @AaronAtDuo I think that was the solution we came up with. We're just going to filter out duo_unix packages on the EPEL repository so that Duo Security repo packages takes precedence

**Comment by AaronAtDuo** [comment]
Closing out this old issue
