### ISSUE TITLE
failmore=secure is ignored when permissions on cfg file are wrong

### ISSUE THREAD

**Issue by JustinAzoff** [duosecurity/duo_unix#88]
This is actually 2 issues, first, I was getting this debug message:

    /etc/duo/pam_duo.conf must be readable only by user 'root'

but the permissions on the file were

    -rw-r-----. 1 root root 250 Nov 15 16:24 /etc/duo/pam_duo.conf

which should have been fine.

The larger issue is that the code that handles the permissions being wrong does:

    i = duo_parse_config(config, __ini_handler, &cfg);
    if (i == -2) {
        duo_syslog(LOG_ERR, "%s must be readable only by user 'root'",
            config);
        return (cfg.failmode == DUO_FAIL_SAFE ? PAM_SUCCESS : PAM_SERVICE_ERR);

However, the code path that returns -2 is:

    if ((st.st_mode & (S_IRGRP|S_IROTH)) != 0) {
        fclose(fp);
        return (-2);
    }
    ret = ini_parse(fp, callback, arg);
    fclose(fp);
    return (ret);

so if the permissions on the file are wrong, it does not read the file cfg all and uses the default value for failmode.

**Comment by xdesai** [comment]
Hello again Justin!
I have a couple thoughts for you. The first is that your permissions for pam_duo.conf have a group read. In Duo Unix we don't allow "group" or "other" permissions to be set on that file.
Removing that group read should fix your issue.
`-rw-------. 1 root root 250 Nov 15 16:24 /etc/duo/pam_duo.conf`

Second, we choose to default to `failmode=safe` because if you mess up your config on Duo Unix you could be locked out of your system and have no way to fix it. Other integrations don't have this problem, but it's a particular case with Duo Unix that we had to address.

Thanks for using Duo and please let us know if you have any other questions.
