### ISSUE TITLE
Allow group permissions on pam_duo.conf?

### ISSUE THREAD

**Issue by adarobin** [duosecurity/duo_unix#91]
I have run into this twice now trying to secure MySQL as well as Spacewalk.  Both of these applications support PAM authentication, but because the application itself is running as an unprivileged user it cannot access /etc/duo/pam_duo.conf.

I have an /etc/pam.d/rhn-satellite containing:
```
#%PAM-1.0
auth        required      pam_env.so
auth        required      pam_sss.so
auth        sufficient    pam_duo.so
auth        required      pam_deny.so
account     sufficient    pam_sss.so
account     required      pam_deny.so
```

However, when I attempt to login to Spacewalk with a user configured to use PAM, I am logged in without using Duo.  I see this in /var/log/messages when I log in:
`Feb  9 20:38:28 spacewalk java: Couldn't open /etc/duo/pam_duo.conf: Permission denied`

I tried doing
```
# chgrp tomcat /etc/duo/pam_duo.conf
# chmod g+r /etc/duo/pam_duo.conf
```

But then I see this in /var/log/messages
`Feb  9 20:39:07 spacewalk java: /etc/duo/pam_duo.conf must be readable only by user 'root'`

I could use Duo Authentication Proxy and then configure the service to use pam_ldap or pam_radius, but that seems silly when I am going to configure pam_duo on the box anyways for SSH.

**Comment by xdesai** [comment]
Hi Adam,
What you're seeing is intentional behavior on our part. `pam_duo.conf` contains a secret (the skey) so we do not want this file readable by any user other than root. Very similar to how you would keep the hashed password file on a unix box only readable by the root user. If you continue to have trouble with this situation please contact support and hopefully we can help you further.
support@duo.com

Thanks for using Duo!
